# Generated by Django 6.0 on 2025-12-23 14:25
from django.db import migrations


def add_topics(apps, schema_editor):
    Topic = apps.get_model('topics', 'Topic')
    topics_data = ['Python', 'Django', 'DevOps']

    # 4. Создаём каждую тему
    for topic_name in topics_data:
        Topic.objects.get_or_create(name=topic_name)


def remove_topics(apps, schema_editor):
    Topic = apps.get_model('topics', 'Topic')
    Topic.objects.filter(name__in=['Python', 'Django', 'DevOps']).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_topics, remove_topics),
    ]